### ISSUE TITLE
Support Passing kwargs Through app.Delay

### ISSUE THREAD

**Issue by rawberg** [marselester/gopher-celery#5]
Thanks again for merging GoRedis support. Wanted to get your take on how you'd like to see `kwargs` passed through when creating a task and I'll create a PR to support it.

This option puts `kwargs` ahead of args which is counter intuitive to the way it works in Python.
```
func (a *App) Delay(path, queue string, kwargs map[string]interface{}, args ...interface{}) error {
	m := protocol.Task{
		ID:     uuid.NewString(),
		Name:   path,
		Kwargs: kwargs,
		Args:   args,
	}
```

We could also consider adding an additional struct method to `App` that's more intuitive. What are your thoughts?

**Comment by marselester** [comment]
I was planning to add `ApplyAsync()` method, here you go https://github.com/marselester/gopher-celery/blob/main/celery.go#L111.

```go
err := app.ApplyAsync("mytask", "important", &celery.AsyncParam{
	Kwargs: map[string]interface{}{"k": "v"},
})
```

I hope this will help.

**Comment by rawberg** [comment]
That works! Thank you! Closing this out.
